### PR TITLE
Add typings.

### PR DESCRIPTION
**Pull request by nichtverstehen**

### CODE REVIEW

**Comment by anton-rudeshko** [comment]
Thank you for your contribution. I'll publish new version shortly.

**Comment by nichtverstehen** [comment]
Nice! Thanks for the quick turnaround!

**Comment by anton-rudeshko** [comment]
@nichtverstehen please have a look

https://github.com/anton-rudeshko/node-throw/releases/tag/v1.1.1

**Comment by nichtverstehen** [comment]
Looking back, I should have named it `index.d.ts` instead of `throw.d.ts` to match the main file. But Typescript gracefully picks all definitions in its compilation scope, so what we have now works.

**Pull request merged**
